### PR TITLE
First pass at asserts

### PR DESCRIPTION
**Pull request by lqd**
The lack of user message, the generated console message and trace are less useful without the ability to print characters when the assert fails, but the interpreter does trap when it needs to!

Here you go @eholk, it is still interesting for the tests — even though we might now need a run-fail to check that assert fails :)

### CODE REVIEW

**Comment by brson** [comment]
lgtm

**Comment by lqd** [comment]
an interesting question we should keep in mind for the future: should panic! also unwind and call drop everywhere ?

**Comment by lqd** [comment]
After thinking about panic! for some time: while the assert! as implemented here works, the more general case of panic! will probably have to be tweaked a bit.
Here a diverging function will return void in wasm, and any rust call to panic! to not require returning a value will cause a problem: wasm will validate that all paths return a value, except if one of the paths is the unreachable node, which is used in the $crate::panic() code, but AFAICT, and I don't know the spec on this, calling a function that will trigger unreachable is not itself considered (at least by binaryen) the same as triggering unreachable, therefore the module could be seen as not valid. This can be mitigated by emitting unreachable directly instead of the panic fn — but has interesting ramifications with the previous comment: if panic has to unwind and drop, then we might have to emit both the fn call and the unreachable node.
That being said, there is a MIR an Unreachable TerminatorKind which I think will be useful to handle those cases I describe, however said terminator is not available in the nightly we use.
We _really_ have to update :)

**Comment by lqd** [comment]
Turns out there's **also** an Assert TerminatorKind in more recent nightlies!

**Comment by brson** [comment]
LLVM at least is able to mark functions as non-returning. I don't know what binaryen's facilities for unwinding are but it must support it somehow.

Punting on unwinding for quite a while is reasonable. You can get a lot done without it.

**Comment by lqd** [comment]
@brson indeed, I was just noting those things both dropping and unwinding, as I was looking at the Unreachable validation and its impact on the general panic! impl — probably for another PR! (but my tests indicate this general panic! will be a requirement to compile libcore)

**Pull request merged**
