### PR TITLE
Add sub, mul, and div operators

### PR DESCRIPTION
**Pull request by lqd**
This PR adds those 3 operators, and also asks a lot of questions :)

An example of the wast output (manually modified to import `print`, call it inside the module, and call the exported test function so that I could check the output in binaryen-shell's interpreter): https://gist.github.com/lqd/44f627530413df83b27815808b953356

First, a comment: I'm not sure about Div. I emitted `i32.div` at first but that made the binaryen checker/interpreter trap, so I switched to `i32.div_s` which worked (maybe @kripken could weigh in on this choice ? and I will modify accordingly).

Second: adding the operators triggered some questions/thoughts
- The fun_types are a set of rust sigs, however those will be converted to wasm func types, and thus will emit duplicates. Probably not that big of a deal, considering binaryen's optimization passes remove a lot of inefficient wasm patterns (even more so in master than the version used in mir2wasm) even though this specific inefficiency of duplicates and unused func types is not yet handled in binaryen IIRC.
- Rust requires those traits & impls to compile, but those operators are wasm "intrinsics", the rust operators' code translated to wasm isn't used (and maybe shouldn't be emitted ? surely not a big deal either, binaryen will optimize them away)
- I was working on/fighting with PartialEq: in mir2wasm a lookup was done on `PartialEq::eq` (eventually, in `trans_fn_name_direct`) but the impls in the module-to-translate were more like `<isize_as_PartialEq>::eq`  -- how should this be handled ? (In my own code I hacked around this by returning the isize PartialEq::eq node id when seeing the PartialEq fn defid, but I doubt very much this is how you guys thought it should work :) -- All in all, this personally allowed me to get back to the BinOp Eq/Ne path and make it work, as well as the AddAssign trait)
- is there a plan on how the missing things in mir2wasm should work ? and at the same time maybe some "issues" would be interesting, so that we see the things you guys could use some help with ? I talked a bit about that on twitter with @kripken yesterday.
  (In my mind I was thinking mir2wasm would maybe use some of emscripten's design to model high level things -- stack frames, memory access, data segments, and so on -- and was waiting for those building blocks to appear before myself contributing on some different topics, having this "plan" and those issues would be helpful in that regard)

### CODE REVIEW

**Comment by brson** [comment]
> First, a comment: I'm not sure about Div. I emitted i32.div at first but that made the binaryen checker/interpreter trap, so I switched to i32.div_s which worked (maybe @kripken could weigh in on this choice ? and I will modify accordingly).

I don't know enough about this to say. In general this code is so early that anything that works is good for progress.

> The fun_types are a set of rust sigs, however those will be converted to wasm func types, and thus will emit duplicates. Probably not that big of a deal, considering binaryen's optimization passes remove a lot of inefficient wasm patterns (even more so in master than the version used in mir2wasm) even though this specific inefficiency of duplicates and unused func types is not yet handled in binaryen IIRC.

I guess this table should be keyed by binaryen types? Seems good to me, though wouldn't we have to create the duplicate binaryen type in order to discover that it hashes to the same value as one we've already seen (defeating the potential optimization)?

> Rust requires those traits & impls to compile, but those operators are wasm "intrinsics", the rust operators' code translated to wasm isn't used (and maybe shouldn't be emitted ? surely not a big deal either, binaryen will optimize them away)

For primitive types rustc emits the instructions directly and it doesn't matter whether the ops are actually defined, so what you are doing is fine for now.

> I was working on/fighting with PartialEq: in mir2wasm a lookup was done on PartialEq::eq (eventually, in trans_fn_name_direct) but the impls in the module-to-translate were more like <isize_as_PartialEq>::eq -- how should this be handled ? (In my own code I hacked around this by returning the isize PartialEq::eq node id when seeing the PartialEq fn defid, but I doubt very much this is how you guys thought it should work :) -- All in all, this personally allowed me to get back to the BinOp Eq/Ne path and make it work, as well as the AddAssign trait)

Perhaps @eddyb @nagisa @solson or @Aatch could help here.

Relatedly, should mir2wasm move to using the item collector now and not deal with monomorphisations itself? Do any of you have pointers on how to use it?

> is there a plan on how the missing things in mir2wasm should work ? and at the same time maybe some "issues" would be interesting, so that we see the things you guys could use some help with ? I talked a bit about that on twitter with @kripken yesterday. (In my mind I was thinking mir2wasm would maybe use some of emscripten's design to model high level things -- stack frames, memory access, data segments, and so on -- and was waiting for those building blocks to appear before myself contributing on some different topics, having this "plan" and those issues would be helpful in that regard)

It would be great to have a plan. Unfortunately, I don't know enough about how either compiler works to know what the steps are. My plan has been to hack things one step at a time by reading the rustc source and bugging the aforementioned people on #rust-internals. Maybe one of them could lay out a vague roadmap.

I would guess that the immediate steps would be to update to Rust master and move to using the item collector to deal with monomorphization (handling monomorphization is one of the biggest sources of ugliness in rustc's old backend, but its new backend has a cleaner way).

**Comment by solson** [comment]
> I was working on/fighting with PartialEq: in mir2wasm a lookup was done on `PartialEq::eq` (eventually, in trans_fn_name_direct) but the impls in the module-to-translate were more like `<isize_as_PartialEq>::eq` -- how should this be handled ? (In my own code I hacked around this by returning the isize PartialEq::eq node id when seeing the PartialEq fn defid, but I doubt very much this is how you guys thought it should work :) -- All in all, this personally allowed me to get back to the BinOp Eq/Ne path and make it work, as well as the AddAssign trait)

I don't quite understand the question but it seems to be a problem with method lookup.

@brson Does mir2wasm have code for trait method lookup, like [this partially-implemented code in Miri](https://github.com/solson/miri/blob/master/src/interpreter/mod.rs#L251-L300) which was copied from somewhere in MIR trans?

If not, I think you need that to handle methods like `eq` properly. (But it would be better to copy from rustc MIR trans than miri - I've hacked it up a bit to suit an interpreter.)

**Comment by brson** [comment]
> @brson Does mir2wasm have code for trait method lookup, like this partially-implemented code in Miri which was copied from somewhere in MIR trans?

Nope!

**Comment by kripken** [comment]
> First, a comment: I'm not sure about Div. I emitted i32.div at first but that made the binaryen checker/interpreter trap, so I switched to i32.div_s which worked (maybe @kripken could weigh in on this choice ? and I will modify accordingly).

Integer division must be signed or unsigned, and it can trap on things like `0/0` or signed underflow. If you don't want it to trap, you can emit something like a check for `0/0` and avoid the div in that case.

Might be ok to not worry about corner cases for now though. But what was the trap being hit - what values were being divided?

>  (In my mind I was thinking mir2wasm would maybe use some of emscripten's design to model high level things -- stack frames, memory access, data segments, and so on -- and was waiting for those building blocks to appear before myself contributing on some different topics, having this "plan" and those issues would be helpful in that regard)

There are open questions here I think. One approach is to not use any emscripten bits, which would mean we emit a pure wasm module. And it's 100% up to rust how that works. Alternatively, if we integrate with emscripten, then we can get all its libraries like webgl, websockets, and all the other web integration. If we go that route, then emscripten has some assumptions about how the stack works, etc., which would be a small amount of integration work instead of a lot more work.

In both cases we would need to emit stack handling code here, which means deciding where to store the stack pointer in memory, and emit code to use it in function preludes etc.

For heap allocation, if we integrate with emscripten then we can use it's malloc implementation.

@brson: maybe you could enable issues in this repo, and we'll open issues for the separate topics?

**Comment by lqd** [comment]
@kripken I must have been doing something stupid, but this was causing an "Abort trap: 6": https://gist.github.com/lqd/cdce63fbbaa6833d9f5040ac95ddc451 while div_s worked immediately.

**Comment by brson** [comment]
Issues are enabled.

**Comment by kripken** [comment]
@lqd: odd, it shouldn't be possible for binaryen to emit that. There is just `i32.div_s` and `i32.div_u`, as integer division must be signed or unsigned. (Float division can be just `f32.div`, on the other hand.) And the functions generating them are `BinaryenDivSInt32`, `BinaryenDivUInt32`. How did you get it to emit an integer div without being signed or unsigned?

@brson: thanks!

**Comment by lqd** [comment]
@kripken I just called the BinaryenDiv extern (https://github.com/brson/mir2wasm/blob/master/src/binaryen.rs#L130) where the other operators are translated. Now the trap makes perfect sense

**Comment by kripken** [comment]
Oh ok, I see. Meanwhile I also noticed that the names changed, from the ambiguous `Div` that misled you to the current names which have the full type in them like `DivSInt32`, `DivFloat32`, etc., which we'll get when we update binaryen.

**Comment by eddyb** [comment]
> In both cases we would need to emit stack handling code here, which means deciding where to store the stack pointer in memory, and emit code to use it in function preludes etc.

I think the "obvious" solution that can easily allow cross-compile-unit interaction is to put a 32-bit stack pointer at `0xffff_fffc` and start the stack just below that. That does require initialization, though.
If address `0` is available, using that instead would make some things easier, assuming a default of `0`.

If `mir2wasm` has to do anything hacky in the interim, it should be abstracted into function prelude/return and "allocate space this big for a stack local" (i.e. like LLVM's `alloca`).

**Comment by lqd** [comment]
@kripken just to be sure as I'm updating binaryen to a more recent version to have those new names: the currently used binaryen has e.g `BinaryenAdd()` but emitted `i32.add` ? (and it's now the job of `BinaryenAddInt32()`)

**Comment by kripken** [comment]
Yes, in latest binaryen, there is a type on those operations, to remove ambiguity. The old `BinaryenAdd` could work for all types, and the new way is to use `BinaryenAddInt32`, for `i32` values, etc.

**Comment by lqd** [comment]
@kripken thank you! So I think the update should be that simple https://github.com/brson/mir2wasm/pull/13

**Pull request merged**
